### PR TITLE
Enforce formatting

### LINKED ISSUE #249: Consider running & enforcing shfmt
shfmt (https://github.com/mvdan/sh) is a formatter for shell scripts.

Perhaps sbt-extras should run it and enforce it in CI.

### PR DESCRIPTION
**Pull request by NeQuissimus**
Fixes #249

### CODE REVIEW

**Comment by dwijnand** [comment]
Thanks for getting the ball rolling on this one!

I think we should add `-kp`, WDYT?  I've found that with some massaging the result is reasonable.

**Comment by NeQuissimus** [comment]
I don't mind that at all, sounds good to me.

**Comment by dwijnand** [comment]
😕 not sure how I broke it...

**Comment by NeQuissimus** [comment]
Is it just a matter of a flaky build?

**Pull request merged**
