### PR TITLE
Use sbt ivy-snapshots repo for timestamped sbt versions

### PR DESCRIPTION
**Pull request by dwijnand**
Use the sbt snapshots repo for timestamped versions, ie. of shape `*-yyyymmdd-hhMMss`, such as https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.10-20151229-205306/.

### CODE REVIEW

**Comment by fommil** [comment]
:+1:

**Comment by fommil** [comment]
@dwijnand would it make sense to use the local jar, e.g. `$HOME/.ivy2/local/org.scala-sbt/sbt-launch/0.13.10-SNAPSHOT/jars/sbt-launch.jar` if `SNAPSHOT` is in the name? as per https://github.com/sbt/sbt/blob/1.0.x/CONTRIBUTING.md

it would make it a lot easier to hack on `sbt` itself.

**Comment by dwijnand** [comment]
@fommil Yep absolutely, makes sense (in a separate PR, yours or mine :P)

**Comment by fommil** [comment]
@dwijnand yours, I've pested Paul enough this week :smile:

**Comment by dwijnand** [comment]
Need to rework this, because as it stands it means that if `sbt.version` is set to a timestamp then `-sbt-launch-repo` is effectively ignored.

**Comment by paulp** [comment]
I want very much to believe bash offers a better way to express this than `[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]` but I don't actually know that it does.

**Comment by dwijnand** [comment]
Sadly that seems to be the only option. Even `extglob` doesn't help.

Best I can do is add a comment next to it indicating it's intended to match `yyyymmdd-hhMMss`.

Speaking of which I did previously define things like `[0-1][0-9]`, `[0-3][0-9]`, etc where the month and day are, but stringed together it was so indecipherable I changed it.

**Comment by dwijnand** [comment]
Ok, updated (and rebased) this so that `-sbt-launch-repo` isn't ignored when `sbt.version` ends in a timestamp.

Note I've added a call to `set_sbt_version` in `usage`.

**Pull request merged**
