### PR TITLE
Use HTTPS

### PR DESCRIPTION
**Pull request by sjbog**

### CODE REVIEW

**Comment by dwijnand** [comment]
See #180 for why this is the status quo.

**Comment by sjbog** [comment]
OK, although master already has
`sbt_launch_ivy_snapshot_repo="https://repo.scala-sbt.org/scalasbt/ivy-snapshots"`
https://github.com/paulp/sbt-extras/blob/master/sbt#L22

**Comment by dwijnand** [comment]
That's true, and I don't think I did it consciously: https://github.com/paulp/sbt-extras/commit/16f10bec81655453a6531114c2c40de7a3eb5ee8

**Comment by dwijnand** [comment]
We want to use the canonical URL for these artefacts and dl.bintray.com isn't the canonical URL, so that change isn't right.

**Comment by sjbog** [comment]
Links with proper SSL certificates still don't work. How is possible? Issues with CI connecting to bintray servers?

> dl.bintray.com isn't the canonical URL
https://www.scala-sbt.org/download.html links to bintray as well

Offtopic: how `repo.scala-sbt.org` can be better if it's just a flawed proxy to `dl.bintray`.

**Comment by dwijnand** [comment]
> https://www.scala-sbt.org/download.html links to bintray as well

Where?

> Offtopic: how `repo.scala-sbt.org` can be better if it's just a flawed proxy to `dl.bintray`.

It might be flawed, but it's still the canonical domain.  dl.bintray.com is just the current implementation detail.

**Comment by dwijnand** [comment]
As commented, this is moving to a non-canonical domain, which isn't desired.

**Pull request closed without merging**
