### PR TITLE
Only use https

### PR DESCRIPTION
**Pull request by alexarchambault**
A few things still seem to be downloaded from http:// repos... This PR switches everything to http**s**://. All repositories seems fine with it.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Not sure the CI errors are related to this PR... I'm running into similar errors on projects of mine (https://travis-ci.org/alexarchambault/coursier/jobs/205758906).

**Comment by dwijnand** [comment]
See Paul's comments in 2015: https://github.com/paulp/sbt-extras/pull/109#issuecomment-124860791

**Comment by dwijnand** [comment]
This fixes the tests: https://github.com/alexarchambault/sbt-extras/compare/topic/https...dwijnand:https

@alexarchambault feel free to cherry-pick, and squash.

**Comment by alexarchambault** [comment]
@dwijnand I added your changes, thanks.

**Comment by dwijnand** [comment]
Cool. And Travis CI is passing now.

Let's wait on @paulp to review then, given the concerns he had had:

> Historically https brings breakage with it. It's not a safe change.

**Comment by paulp** [comment]
There was a major outage of some kind since I made that comment which was tied to the usage of https, like travis failing for everyone for a while. I don't remember the details. If anyone knows what I'm talking about I'd like to review what happened there and be convinced I shouldn't worry about similar things occurring in the future.

**Comment by dwijnand** [comment]
I don't remember all the details. I didn't know some at the time, and I've forgotten some since.

What I remember (and can find) is that Travis was failing for everyone because http://typesafe.artifactoryonline.com had been decommissioned, with sbt-extras still using it. The new canonical domain was to be repo.typesafe.com. I think that suffered a couple of outages/downtimes.

https://repo.typesafe.com works, and it's what the sbt launcher uses, to download sbt:

```
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.13/jars/main.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#main;0.13.13!main.jar (2788ms)
```

**Comment by paulp** [comment]
It's this I was thinking of: failing on redirects. https://github.com/sbt/sbt/issues/2758

**Comment by dwijnand** [comment]
That one was on Bintray. They were sporadically redirecting https dl.bintray.com to http akamai.bintray.com, which on the JVM is denied.

**Comment by paulp** [comment]
It will also interact with proxies, do we know how?

**Comment by alexarchambault** [comment]
The point of using https here is just security... Almost every Scala developer has / will have downloaded things though sbt-extras. As no signature of any kind is checked for these, https is the only thing that prevents trivial man-in-the-middle attacks. https being the default should be a no brainer IMO.

**Comment by paulp** [comment]
@alexarchambault I don't need any persuasion that in the absence of anything breaking, https is better than not.

**Comment by dwijnand** [comment]
We have a number of fallbacks in place in case this breaks (again): sbt launcher jar caching, `-sbt-launch-repo`, `-sbt-jar` and `-sbt-launch-dir`.

If I were flying solo I'd merge this, and revert if something came up.

But I'm not going to be upset if we don't - I don't feel strongly about it. This isn't my fight.

**Comment by paulp** [comment]
Can it try https and fall back to http (with a warning) if https fails for whatever reason? That would be good enough for me.

**Comment by alexarchambault** [comment]
An automatic fallback to http would allow for a man-in-the-middle attack it seems (an attacker can block some https requests, and wait for the http requests to be made). A manual one could be fine though... (users would know something wrong might be going on).

Switching to https, even if there's a risk it might break things under some conditions, would be fine for me (for security reasons). I don't feel like fighting too hard for it either, though...

**Comment by paulp** [comment]
If the failure mode is transparent and offers an easy remedy (say, a command line option which switches over to non-https targets) then I can merge it in good conscience. But I don't want to just switch it and gamble there is no impact.

**Comment by dwijnand** [comment]
I'm going to close this. But we'd be love for this to be resubmitted (by @alexarchambault or anyone) with @paulp's easy remedy idea.

**Pull request closed without merging**
