### PR TITLE
Add sbt-purge

### PR DESCRIPTION
**Pull request by dwijnand**
@paulp WDYT? Happy for this to live here?

### CODE REVIEW

**Comment by paulp** [comment]
Any script which contains "rm -r" needs to be much more paranoid. Running under `-e` at an absolute minimum.

Regardless of the need for this or the details of its implementation, I don't really want to expand the bash footprint of this repo further.

**Comment by paulp** [comment]
`rm -r $path` will fail, possibly horribly, on any file with a space in it. Here's a nice legal filename: `himom ..`.

**Comment by dwijnand** [comment]
No worries. Thanks for the tips. What do you mean by "under `-e`"?

**Comment by dwijnand** [comment]
lol I even quoted it under `--dry-run` but forgot to quote it for real..

**Comment by dwijnand** [comment]
> Exit immediately if a pipeline (which may consist of a single simple command), a subshell command enclosed in parentheses, or one of the commands executed as part of a command list enclosed by braces (see SHELL GRAMMAR above) exits with a non-zero status.

Found it.

**Pull request closed without merging**
