### PR TITLE
cygwin support

### PR DESCRIPTION
**Pull request by pawelpanasewicz**
Anything against this? Now I can run it as well from windows.

### CODE REVIEW

**Comment by paulp** [comment]
Does travis offer any way to test it?

**Comment by xuwei-k** [comment]
Maybe appveyor support windows and cygwin.

https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin

**Comment by pawelpanasewicz** [comment]
Hi!
Can we test it? 

Automated testing after each commit in CI requires some work and decisions.

**Firstly** - *bats* must be able to run under cygwin in order to run sbt-extras' tests which will prove that it behaves nicely under cygwin. 

There is some work done (in **LeahCim/bats** fork) towards this direction, but it's not merged so far.  **LeahCim/bats** is developed practically on top of master of original **sstephenson/bats** (it does not contain changes from particular text file). On the other hand _LeahCim/bats_ is not fully compatible but maybe it's enough to test _sbt-extras_ and it's worth to use it for price of having tested cygwin.
See [PR128](https://github.com/sstephenson/bats/pull/128). 

**Secondly** - it has to be run on agent which supports cygwin. As @xuwei-k notices approyer is one possible choice. 

Let me do some research on "firstly" thing.
What is your opinion?

**Comment by pawelpanasewicz** [comment]
I am almost there. 

This is build log from appveyor which runs test under cygwin on windows.
https://ci.appveyor.com/project/pawelpanasewicz/sbt-extras/build/1.0.13

Tests are mainly failing with assertion messages very similar to this one:
```
# expected:
# Downloading sbt launcher for 0.12.2:
#   From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.12.2/sbt-launch.jar
#     To  $ROOT/.sbt/launchers/0.12.2/sbt-launch.jar
# 
# actual:
# Downloading sbt launcher for 0.12.2:
#   From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.12.2/sbt-launch.jar
#     To  C:\cygwin64\tmp\download.bats.744\.sbt\launchers\0.12.2\sbt-launch.jar
```
As one can see only prefix of _To some_path_ are different.

This is because `normalize_paths` doesn't normalize windows like paths. This is code of `normalize_paths`:

```
normalize_paths () {
  stdin_or_args "$@" | \
    sed "s:$TEST_ROOT:\$ROOT:g" | \
    sed "s:$HOME:\$ROOT:g"
}
``` 

Windows like path in this example is  `C:\cygwin64\tmp\download.bats.744\.sbt\launchers\0.12.2\sbt-launch.jar`. We need to normalize it into `$ROOT/.sbt/launchers/0.12.2/sbt-launch.jar`. 
How to do this? 
The command `cygpath -w $TEST_ROOT` called from scope of mentioned function can help. It returns wanted prefix of windows style path, in this example it is `C:\cygwin64\tmp\download.bats.744`. 

Now it is sufice to make some replacement in `normalize_paths` and it should work. 

The tricky part for me is that I don't know how to use `sed` in order to replace this from input string. 

Can someone help?

**Comment by paulp** [comment]
@pawelpanasewicz If I understand correctly having barely skimmed and running out the door, this might do it. Replace `sed "s:$TEST_ROOT:\$ROOT:g"` with 
```
sed "s:$(cygpath -w "$TEST_ROOT"):\$ROOT:g"
```

**Comment by pawelpanasewicz** [comment]
@paulp Thanks! I've manage to run it. 

Unfortunately tests are not passing. At first glance outputs are the same. I did some CRLF => LF convertion hoping it will solve the problem but it didn't helped. Not sure what can cause problems.

https://ci.appveyor.com/project/pawelpanasewicz/sbt-extras/build/1.0.22

Briefly some test failures look like this:
```
not ok 2 tolerates blank lines and comments in jvm_opts file
# (in test file test/config-file.bats, line 33)
#   `expectedOutput | assert_output' failed
# /cygdrive/c/sbt-extras/test/test_helper.bash: line 131: warning: add_process: pid  2080 (stdin_or_args "$@") marked as still alive
# 
# expected:
# -Xmx1g
# -Dsome.prop="pass a # in a string"
# -Xss4m
# -Xms1g
# -jar
# $ROOT/.sbt/launchers/0.13.12/sbt-launch.jar
# about
# 
# actual:
# -Xmx1g
# -Dsome.prop="pass a # in a string"
# -Xss4m
# -Xms1g
# -jar
# $ROOT/.sbt/launchers/0.13.12/sbt-launch.jar
# about
# 
```

**Comment by pawelpanasewicz** [comment]
It looks like we have sbt-extras working under both linux and cygwin.
Travis and Appveyor managed to test it successfully.

https://ci.appveyor.com/project/pawelpanasewicz/sbt-extras/build/1.0.38
https://travis-ci.org/jawp/sbt-extras/builds/165897944

**Comment by paulp** [comment]
@pawelpanasewicz Great work! It restores a little of my faith in humanity to see a contribution of this kind. Probably I have to flip a switch somewhere to enable appveyor tests?

**Comment by paulp** [comment]
Okay, I think I have appveyor set up, but the easiest way to test that is to merge this so that's what I'm doing.

**Comment by dwijnand** [comment]
Nice one @pawelpanasewicz!

**Comment by pawelpanasewicz** [comment]
Thanks guys! Nice to read such words!

**Pull request merged**
