### PR TITLE
Remove some default jvm options.

### PR DESCRIPTION
**Pull request by paulp**
Based in part on

  http://xmlandmore.blogspot.com/2014/08/jdk-8-revisiting-reservedcodecachesize.html

I think these options are doing more harm than good and need to be
remotivated or removed.

### CODE REVIEW

**Comment by dwijnand** [comment]
Source:

* `-XX:+CMSClassUnloadingEnabled`: https://github.com/paulp/sbt-extras/commit/0920f5dda87e30f388b585f13fb604efc154f9d4#diff-a5e388b571c7217d2e0ee0435a55a550R11
* `-XX:+UseConcMarkSweepGC`: https://github.com/paulp/sbt-extras/pull/40
* `-XX:ReservedCodeCacheSize`: https://github.com/paulp/sbt-extras/commit/71010f00b2a26b8da7ae058f8401768e8b49306b

**Comment by paulp** [comment]
I should have mentioned I'm viewing this from an only-care-about-java8 perspective.

**Comment by dwijnand** [comment]
Personally I'm fine with that viewpoint.

I just remember CMSClassUnloadingEnabled being a big big thing a few years ago. Sure we don't need it now?

**Comment by paulp** [comment]
I am sure of nothing. I just think we should flip the burden of proof.

**Comment by dwijnand** [comment]
Alright. LGTM. If anything comes up, revert is only a short commit away.

**Pull request merged**
